# Run tests and dialyzer

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux:
    name: Test on OTP ${{ matrix.otp_version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: [21,22,23]
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: make
      - name: Test
        run: make test
      - name: XRef
        run: make xref
      - name: Dialyzer
        run: make dialyzer
